### ISSUE TITLE
Where can I get this paper?

### ISSUE THREAD

**Issue by david-liao** [mdbsk/continual-learning-in-nlp#1]
I'm interested with this work. Does it has been published on any place where I can get it?

**Comment by mbiesialska** [comment]
Hi David, thanks for your interest in our work. 
Our paper has been accepted at [COLING 2020](https://coling2020.org/), so the final version of the paper will be available in COLING proceedings on [ACL Anthology](https://aclweb.org/anthology/) in 1 month.
In case you want to read our paper earlier, then please share with me your email address.

**Comment by david-liao** [comment]
Hi, Magdalena, thanks for your quick reply.
My email address is junwei.liao@gmail.com. Thanks for sharing the paper.

Magdalena Biesialska <notifications@github.com> 于2020年11月13日周五 下午7:15写道：
